version: '3.7'

services:
  web-ui:
    image: 'react-app-test'
    build:
      target: development-build-stage
    ports:
      - '5173:5173'
    volumes:
      - ./:/app
      - /app/node_modules

