version: '3.7'

services:
  web-ui:
    image: 'react-app-test'
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    # ports:
    #   - '80:80'
    restart: 'unless-stopped'

